name: MarmaladeQuests
version: '0.0.1-ALPHA'
main: com.abdullahcxd.mmq.MarmaladeQuests
api-version: '1.21'
description: One of a kind plugin that powers any survival like server with quests, abilities and so on.

commands:
  marmalade:
    description: The main command for the MarmaladeQuests Plugin
    aliases:
      - mq
      - mmq
      - marmaladequests

libraries:
  - com.github.lalyos:jfiglet:0.0.9
  - com.zaxxer:HikariCP:7.0.2
  - org.json:json:20250517